// Generated by https://quicktype.io

export interface ListPrintersResponse {
  name: string;
  portName: string;
  driverName: string;
  printProcessor: string;
  datatype: string;
  status: any[];
  statusNumber: number;
  attributes: string[];
  priority: number;
  defaultPriority: number;
  averagePPM: number;
  shareName?: string;
}
